name: test github action
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'CI Number'
        required: true
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Enable Python ${{ env.python-version }}
        uses: actions/setup-python@v2
        env:
          python-version: 3.7
        with:
          python-version: ${{ env.python-version }}

      - name: run python code with output
        id: run-py
        run: |
          py=`python test.py ${{ github.event.inputs.name }}`
          echo '::set-output name=success::$(echo $py)'
          

      - name: print python output

        if: steps.run-py.outputs.success == 'Hello World'
        run: |
          echo "success true"

