name: test github action
on:
  workflow_dispatch:
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Enable Python ${{ env.python-version }}
        uses: actions/setup-python@v2
        env:
          python-version: 3.7
        with:
          python-version: ${{ env.python-version }}
      - name: run python code with param
        env: 
          input1: ll
        run: |
          python test.py $input1

